/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.PetroVaultHD.Model.ETP.Custom;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ChannelQueryOptions extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChannelQueryOptions\",\"namespace\":\"Petrolink.PetroVaultHD.Model.ETP.Custom\",\"fields\":[{\"name\":\"startIndex\",\"type\":[\"null\",\"long\"]},{\"name\":\"endIndex\",\"type\":[\"null\",\"long\"]}],\"fullName\":\"Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long startIndex;
  @Deprecated public java.lang.Long endIndex;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ChannelQueryOptions() {}

  /**
   * All-args constructor.
   */
  public ChannelQueryOptions(java.lang.Long startIndex, java.lang.Long endIndex) {
    this.startIndex = startIndex;
    this.endIndex = endIndex;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return startIndex;
    case 1: return endIndex;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: startIndex = (java.lang.Long)value$; break;
    case 1: endIndex = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'startIndex' field.
   */
  public java.lang.Long getStartIndex() {
    return startIndex;
  }

  /**
   * Sets the value of the 'startIndex' field.
   * @param value the value to set.
   */
  public void setStartIndex(java.lang.Long value) {
    this.startIndex = value;
  }

  /**
   * Gets the value of the 'endIndex' field.
   */
  public java.lang.Long getEndIndex() {
    return endIndex;
  }

  /**
   * Sets the value of the 'endIndex' field.
   * @param value the value to set.
   */
  public void setEndIndex(java.lang.Long value) {
    this.endIndex = value;
  }

  /** Creates a new ChannelQueryOptions RecordBuilder */
  public static Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder newBuilder() {
    return new Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder();
  }
  
  /** Creates a new ChannelQueryOptions RecordBuilder by copying an existing Builder */
  public static Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder newBuilder(Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder other) {
    return new Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder(other);
  }
  
  /** Creates a new ChannelQueryOptions RecordBuilder by copying an existing ChannelQueryOptions instance */
  public static Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder newBuilder(Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions other) {
    return new Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder(other);
  }
  
  /**
   * RecordBuilder for ChannelQueryOptions instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChannelQueryOptions>
    implements org.apache.avro.data.RecordBuilder<ChannelQueryOptions> {

    private java.lang.Long startIndex;
    private java.lang.Long endIndex;

    /** Creates a new Builder */
    private Builder() {
      super(Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.startIndex)) {
        this.startIndex = data().deepCopy(fields()[0].schema(), other.startIndex);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.endIndex)) {
        this.endIndex = data().deepCopy(fields()[1].schema(), other.endIndex);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ChannelQueryOptions instance */
    private Builder(Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions other) {
            super(Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.SCHEMA$);
      if (isValidValue(fields()[0], other.startIndex)) {
        this.startIndex = data().deepCopy(fields()[0].schema(), other.startIndex);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.endIndex)) {
        this.endIndex = data().deepCopy(fields()[1].schema(), other.endIndex);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'startIndex' field */
    public java.lang.Long getStartIndex() {
      return startIndex;
    }
    
    /** Sets the value of the 'startIndex' field */
    public Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder setStartIndex(java.lang.Long value) {
      validate(fields()[0], value);
      this.startIndex = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'startIndex' field has been set */
    public boolean hasStartIndex() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'startIndex' field */
    public Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder clearStartIndex() {
      startIndex = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'endIndex' field */
    public java.lang.Long getEndIndex() {
      return endIndex;
    }
    
    /** Sets the value of the 'endIndex' field */
    public Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder setEndIndex(java.lang.Long value) {
      validate(fields()[1], value);
      this.endIndex = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'endIndex' field has been set */
    public boolean hasEndIndex() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'endIndex' field */
    public Petrolink.PetroVaultHD.Model.ETP.Custom.ChannelQueryOptions.Builder clearEndIndex() {
      endIndex = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ChannelQueryOptions build() {
      try {
        ChannelQueryOptions record = new ChannelQueryOptions();
        record.startIndex = fieldSetFlags()[0] ? this.startIndex : (java.lang.Long) defaultValue(fields()[0]);
        record.endIndex = fieldSetFlags()[1] ? this.endIndex : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
