/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.WITSML.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ChannelType { 
  Raw, Alias, Synthetic, Derived, Downsampled, Threshold, Event  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChannelType\",\"namespace\":\"Petrolink.WITSML.Datatypes\",\"symbols\":[\"Raw\",\"Alias\",\"Synthetic\",\"Derived\",\"Downsampled\",\"Threshold\",\"Event\"],\"fullName\":\"Petrolink.WITSML.Datatypes.ChannelType\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
