/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.WITSML.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ChannelIndexDirection { 
  Decreasing, Increasing, Unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChannelIndexDirection\",\"namespace\":\"Petrolink.WITSML.Datatypes\",\"symbols\":[\"Decreasing\",\"Increasing\",\"Unknown\"],\"fullName\":\"Petrolink.WITSML.Datatypes.ChannelIndexDirection\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
