/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.WITSML.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ChannelIndexType { 
  Byte, Datetime, Double, Float, Int, Long, Short, String, String40, String16, Unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChannelIndexType\",\"namespace\":\"Petrolink.WITSML.Datatypes\",\"symbols\":[\"Byte\",\"Datetime\",\"Double\",\"Float\",\"Int\",\"Long\",\"Short\",\"String\",\"String40\",\"String16\",\"Unknown\"],\"fullName\":\"Petrolink.WITSML.Datatypes.ChannelIndexType\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
