/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.WITSML.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ChannelStatus { 
  Active, Inactive, Closed  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChannelStatus\",\"namespace\":\"Petrolink.WITSML.Datatypes\",\"symbols\":[\"Active\",\"Inactive\",\"Closed\"],\"fullName\":\"Petrolink.WITSML.Datatypes.ChannelStatus\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
