/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.WITSML.Events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ChannelStatusChanged extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChannelStatusChanged\",\"namespace\":\"Petrolink.WITSML.Events\",\"fields\":[{\"name\":\"channelId\",\"type\":{\"type\":\"fixed\",\"name\":\"UUID\",\"namespace\":\"Petrolink.Datatypes\",\"size\":16,\"fullName\":\"Petrolink.Datatypes.UUID\",\"depends\":[]}},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"ChannelStatus\",\"namespace\":\"Petrolink.WITSML.Datatypes\",\"symbols\":[\"Active\",\"Inactive\",\"Closed\"],\"fullName\":\"Petrolink.WITSML.Datatypes.ChannelStatus\",\"depends\":[]}}],\"fullName\":\"Petrolink.WITSML.Events.ChannelStatusChanged\",\"depends\":[\"Petrolink.Datatypes.UUID\",\"Petrolink.WITSML.Datatypes.ChannelStatus\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public Petrolink.Datatypes.UUID channelId;
  @Deprecated public Petrolink.WITSML.Datatypes.ChannelStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ChannelStatusChanged() {}

  /**
   * All-args constructor.
   */
  public ChannelStatusChanged(Petrolink.Datatypes.UUID channelId, Petrolink.WITSML.Datatypes.ChannelStatus status) {
    this.channelId = channelId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channelId;
    case 1: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channelId = (Petrolink.Datatypes.UUID)value$; break;
    case 1: status = (Petrolink.WITSML.Datatypes.ChannelStatus)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'channelId' field.
   */
  public Petrolink.Datatypes.UUID getChannelId() {
    return channelId;
  }

  /**
   * Sets the value of the 'channelId' field.
   * @param value the value to set.
   */
  public void setChannelId(Petrolink.Datatypes.UUID value) {
    this.channelId = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public Petrolink.WITSML.Datatypes.ChannelStatus getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(Petrolink.WITSML.Datatypes.ChannelStatus value) {
    this.status = value;
  }

  /** Creates a new ChannelStatusChanged RecordBuilder */
  public static Petrolink.WITSML.Events.ChannelStatusChanged.Builder newBuilder() {
    return new Petrolink.WITSML.Events.ChannelStatusChanged.Builder();
  }
  
  /** Creates a new ChannelStatusChanged RecordBuilder by copying an existing Builder */
  public static Petrolink.WITSML.Events.ChannelStatusChanged.Builder newBuilder(Petrolink.WITSML.Events.ChannelStatusChanged.Builder other) {
    return new Petrolink.WITSML.Events.ChannelStatusChanged.Builder(other);
  }
  
  /** Creates a new ChannelStatusChanged RecordBuilder by copying an existing ChannelStatusChanged instance */
  public static Petrolink.WITSML.Events.ChannelStatusChanged.Builder newBuilder(Petrolink.WITSML.Events.ChannelStatusChanged other) {
    return new Petrolink.WITSML.Events.ChannelStatusChanged.Builder(other);
  }
  
  /**
   * RecordBuilder for ChannelStatusChanged instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChannelStatusChanged>
    implements org.apache.avro.data.RecordBuilder<ChannelStatusChanged> {

    private Petrolink.Datatypes.UUID channelId;
    private Petrolink.WITSML.Datatypes.ChannelStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(Petrolink.WITSML.Events.ChannelStatusChanged.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Petrolink.WITSML.Events.ChannelStatusChanged.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channelId)) {
        this.channelId = data().deepCopy(fields()[0].schema(), other.channelId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ChannelStatusChanged instance */
    private Builder(Petrolink.WITSML.Events.ChannelStatusChanged other) {
            super(Petrolink.WITSML.Events.ChannelStatusChanged.SCHEMA$);
      if (isValidValue(fields()[0], other.channelId)) {
        this.channelId = data().deepCopy(fields()[0].schema(), other.channelId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'channelId' field */
    public Petrolink.Datatypes.UUID getChannelId() {
      return channelId;
    }
    
    /** Sets the value of the 'channelId' field */
    public Petrolink.WITSML.Events.ChannelStatusChanged.Builder setChannelId(Petrolink.Datatypes.UUID value) {
      validate(fields()[0], value);
      this.channelId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'channelId' field has been set */
    public boolean hasChannelId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'channelId' field */
    public Petrolink.WITSML.Events.ChannelStatusChanged.Builder clearChannelId() {
      channelId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public Petrolink.WITSML.Datatypes.ChannelStatus getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public Petrolink.WITSML.Events.ChannelStatusChanged.Builder setStatus(Petrolink.WITSML.Datatypes.ChannelStatus value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'status' field */
    public Petrolink.WITSML.Events.ChannelStatusChanged.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ChannelStatusChanged build() {
      try {
        ChannelStatusChanged record = new ChannelStatusChanged();
        record.channelId = fieldSetFlags()[0] ? this.channelId : (Petrolink.Datatypes.UUID) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (Petrolink.WITSML.Datatypes.ChannelStatus) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
