/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Protocol.ChannelStreaming;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ChannelStreamingStart extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChannelStreamingStart\",\"namespace\":\"Energistics.Protocol.ChannelStreaming\",\"fields\":[{\"name\":\"channels\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ChannelStreamingInfo\",\"namespace\":\"Energistics.Datatypes.ChannelData\",\"fields\":[{\"name\":\"channelId\",\"type\":\"long\"},{\"name\":\"startIndex\",\"type\":{\"type\":\"record\",\"name\":\"StreamingStartIndex\",\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"int\",\"long\"]}],\"fullName\":\"Energistics.Datatypes.ChannelData.StreamingStartIndex\",\"depends\":[]}},{\"name\":\"receiveChangeNotification\",\"type\":\"boolean\"}],\"fullName\":\"Energistics.Datatypes.ChannelData.ChannelStreamingInfo\",\"depends\":[\"Energistics.Datatypes.ChannelData.StreamingStartIndex\"]}}}],\"messageType\":\"4\",\"protocol\":\"1\",\"senderRole\":\"consumer\",\"protocolRoles\":\"producer,consumer\",\"fullName\":\"Energistics.Protocol.ChannelStreaming.ChannelStreamingStart\",\"depends\":[\"Energistics.Datatypes.ChannelData.ChannelStreamingInfo\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo> channels;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ChannelStreamingStart() {}

  /**
   * All-args constructor.
   */
  public ChannelStreamingStart(java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo> channels) {
    this.channels = channels;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channels;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channels = (java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'channels' field.
   */
  public java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo> getChannels() {
    return channels;
  }

  /**
   * Sets the value of the 'channels' field.
   * @param value the value to set.
   */
  public void setChannels(java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo> value) {
    this.channels = value;
  }

  /** Creates a new ChannelStreamingStart RecordBuilder */
  public static Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder newBuilder() {
    return new Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder();
  }
  
  /** Creates a new ChannelStreamingStart RecordBuilder by copying an existing Builder */
  public static Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder newBuilder(Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder other) {
    return new Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder(other);
  }
  
  /** Creates a new ChannelStreamingStart RecordBuilder by copying an existing ChannelStreamingStart instance */
  public static Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder newBuilder(Energistics.Protocol.ChannelStreaming.ChannelStreamingStart other) {
    return new Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder(other);
  }
  
  /**
   * RecordBuilder for ChannelStreamingStart instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChannelStreamingStart>
    implements org.apache.avro.data.RecordBuilder<ChannelStreamingStart> {

    private java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo> channels;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channels)) {
        this.channels = data().deepCopy(fields()[0].schema(), other.channels);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ChannelStreamingStart instance */
    private Builder(Energistics.Protocol.ChannelStreaming.ChannelStreamingStart other) {
            super(Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.SCHEMA$);
      if (isValidValue(fields()[0], other.channels)) {
        this.channels = data().deepCopy(fields()[0].schema(), other.channels);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'channels' field */
    public java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo> getChannels() {
      return channels;
    }
    
    /** Sets the value of the 'channels' field */
    public Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder setChannels(java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo> value) {
      validate(fields()[0], value);
      this.channels = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'channels' field has been set */
    public boolean hasChannels() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'channels' field */
    public Energistics.Protocol.ChannelStreaming.ChannelStreamingStart.Builder clearChannels() {
      channels = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ChannelStreamingStart build() {
      try {
        ChannelStreamingStart record = new ChannelStreamingStart();
        record.channels = fieldSetFlags()[0] ? this.channels : (java.util.List<Energistics.Datatypes.ChannelData.ChannelStreamingInfo>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
