/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Protocol.ChannelStreaming;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ChannelData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChannelData\",\"namespace\":\"Energistics.Protocol.ChannelStreaming\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DataItem\",\"namespace\":\"Energistics.Datatypes.ChannelData\",\"fields\":[{\"name\":\"indexes\",\"type\":{\"type\":\"array\",\"items\":\"long\"}},{\"name\":\"channelId\",\"type\":\"long\"},{\"name\":\"value\",\"type\":{\"type\":\"record\",\"name\":\"DataValue\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"double\",\"float\",\"int\",\"long\",\"string\",{\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}],\"fullName\":\"Energistics.Datatypes.ArrayOfDouble\",\"depends\":[]},\"boolean\",\"bytes\"]}],\"fullName\":\"Energistics.Datatypes.DataValue\",\"depends\":[\"Energistics.Datatypes.ArrayOfDouble\"]}},{\"name\":\"valueAttributes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DataAttribute\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"attributeId\",\"type\":\"int\"},{\"name\":\"attributeValue\",\"type\":\"DataValue\"}],\"fullName\":\"Energistics.Datatypes.DataAttribute\",\"depends\":[\"Energistics.Datatypes.DataValue\"]}}}],\"fullName\":\"Energistics.Datatypes.ChannelData.DataItem\",\"depends\":[\"Energistics.Datatypes.DataValue\",\"Energistics.Datatypes.DataAttribute\"]}}}],\"messageType\":\"3\",\"protocol\":\"1\",\"senderRole\":\"producer\",\"protocolRoles\":\"producer,consumer\",\"fullName\":\"Energistics.Protocol.ChannelStreaming.ChannelData\",\"depends\":[\"Energistics.Datatypes.ChannelData.DataItem\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<Energistics.Datatypes.ChannelData.DataItem> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ChannelData() {}

  /**
   * All-args constructor.
   */
  public ChannelData(java.util.List<Energistics.Datatypes.ChannelData.DataItem> data) {
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.util.List<Energistics.Datatypes.ChannelData.DataItem>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   */
  public java.util.List<Energistics.Datatypes.ChannelData.DataItem> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.List<Energistics.Datatypes.ChannelData.DataItem> value) {
    this.data = value;
  }

  /** Creates a new ChannelData RecordBuilder */
  public static Energistics.Protocol.ChannelStreaming.ChannelData.Builder newBuilder() {
    return new Energistics.Protocol.ChannelStreaming.ChannelData.Builder();
  }
  
  /** Creates a new ChannelData RecordBuilder by copying an existing Builder */
  public static Energistics.Protocol.ChannelStreaming.ChannelData.Builder newBuilder(Energistics.Protocol.ChannelStreaming.ChannelData.Builder other) {
    return new Energistics.Protocol.ChannelStreaming.ChannelData.Builder(other);
  }
  
  /** Creates a new ChannelData RecordBuilder by copying an existing ChannelData instance */
  public static Energistics.Protocol.ChannelStreaming.ChannelData.Builder newBuilder(Energistics.Protocol.ChannelStreaming.ChannelData other) {
    return new Energistics.Protocol.ChannelStreaming.ChannelData.Builder(other);
  }
  
  /**
   * RecordBuilder for ChannelData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChannelData>
    implements org.apache.avro.data.RecordBuilder<ChannelData> {

    private java.util.List<Energistics.Datatypes.ChannelData.DataItem> data;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Protocol.ChannelStreaming.ChannelData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Protocol.ChannelStreaming.ChannelData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ChannelData instance */
    private Builder(Energistics.Protocol.ChannelStreaming.ChannelData other) {
            super(Energistics.Protocol.ChannelStreaming.ChannelData.SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'data' field */
    public java.util.List<Energistics.Datatypes.ChannelData.DataItem> getData() {
      return data;
    }
    
    /** Sets the value of the 'data' field */
    public Energistics.Protocol.ChannelStreaming.ChannelData.Builder setData(java.util.List<Energistics.Datatypes.ChannelData.DataItem> value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'data' field has been set */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'data' field */
    public Energistics.Protocol.ChannelStreaming.ChannelData.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ChannelData build() {
      try {
        ChannelData record = new ChannelData();
        record.data = fieldSetFlags()[0] ? this.data : (java.util.List<Energistics.Datatypes.ChannelData.DataItem>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
