/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Protocol.Discovery;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GetResourcesResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GetResourcesResponse\",\"namespace\":\"Energistics.Protocol.Discovery\",\"fields\":[{\"name\":\"resource\",\"type\":{\"type\":\"record\",\"name\":\"Resource\",\"namespace\":\"Energistics.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"contentType\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"channelSubscribable\",\"type\":\"boolean\"},{\"name\":\"customData\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"resourceType\",\"type\":\"string\"},{\"name\":\"hasChildren\",\"type\":\"int\"},{\"name\":\"uuid\",\"type\":[\"null\",\"string\"]},{\"name\":\"lastChanged\",\"type\":\"long\"},{\"name\":\"objectNotifiable\",\"type\":\"boolean\"}],\"fullName\":\"Energistics.Datatypes.Object.Resource\",\"depends\":[]}}],\"messageType\":\"2\",\"protocol\":\"3\",\"senderRole\":\"store\",\"protocolRoles\":\"store,customer\",\"fullName\":\"Energistics.Protocol.Discovery.GetResourcesResponse\",\"depends\":[\"Energistics.Datatypes.Object.Resource\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public Energistics.Datatypes.Object.Resource resource;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GetResourcesResponse() {}

  /**
   * All-args constructor.
   */
  public GetResourcesResponse(Energistics.Datatypes.Object.Resource resource) {
    this.resource = resource;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return resource;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: resource = (Energistics.Datatypes.Object.Resource)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'resource' field.
   */
  public Energistics.Datatypes.Object.Resource getResource() {
    return resource;
  }

  /**
   * Sets the value of the 'resource' field.
   * @param value the value to set.
   */
  public void setResource(Energistics.Datatypes.Object.Resource value) {
    this.resource = value;
  }

  /** Creates a new GetResourcesResponse RecordBuilder */
  public static Energistics.Protocol.Discovery.GetResourcesResponse.Builder newBuilder() {
    return new Energistics.Protocol.Discovery.GetResourcesResponse.Builder();
  }
  
  /** Creates a new GetResourcesResponse RecordBuilder by copying an existing Builder */
  public static Energistics.Protocol.Discovery.GetResourcesResponse.Builder newBuilder(Energistics.Protocol.Discovery.GetResourcesResponse.Builder other) {
    return new Energistics.Protocol.Discovery.GetResourcesResponse.Builder(other);
  }
  
  /** Creates a new GetResourcesResponse RecordBuilder by copying an existing GetResourcesResponse instance */
  public static Energistics.Protocol.Discovery.GetResourcesResponse.Builder newBuilder(Energistics.Protocol.Discovery.GetResourcesResponse other) {
    return new Energistics.Protocol.Discovery.GetResourcesResponse.Builder(other);
  }
  
  /**
   * RecordBuilder for GetResourcesResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GetResourcesResponse>
    implements org.apache.avro.data.RecordBuilder<GetResourcesResponse> {

    private Energistics.Datatypes.Object.Resource resource;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Protocol.Discovery.GetResourcesResponse.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Protocol.Discovery.GetResourcesResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.resource)) {
        this.resource = data().deepCopy(fields()[0].schema(), other.resource);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GetResourcesResponse instance */
    private Builder(Energistics.Protocol.Discovery.GetResourcesResponse other) {
            super(Energistics.Protocol.Discovery.GetResourcesResponse.SCHEMA$);
      if (isValidValue(fields()[0], other.resource)) {
        this.resource = data().deepCopy(fields()[0].schema(), other.resource);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'resource' field */
    public Energistics.Datatypes.Object.Resource getResource() {
      return resource;
    }
    
    /** Sets the value of the 'resource' field */
    public Energistics.Protocol.Discovery.GetResourcesResponse.Builder setResource(Energistics.Datatypes.Object.Resource value) {
      validate(fields()[0], value);
      this.resource = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'resource' field has been set */
    public boolean hasResource() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'resource' field */
    public Energistics.Protocol.Discovery.GetResourcesResponse.Builder clearResource() {
      resource = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public GetResourcesResponse build() {
      try {
        GetResourcesResponse record = new GetResourcesResponse();
        record.resource = fieldSetFlags()[0] ? this.resource : (Energistics.Datatypes.Object.Resource) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
