/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Protocol.Discovery;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GetResources extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GetResources\",\"namespace\":\"Energistics.Protocol.Discovery\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"}],\"messageType\":\"1\",\"protocol\":\"3\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"fullName\":\"Energistics.Protocol.Discovery.GetResources\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uri;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GetResources() {}

  /**
   * All-args constructor.
   */
  public GetResources(java.lang.CharSequence uri) {
    this.uri = uri;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /** Creates a new GetResources RecordBuilder */
  public static Energistics.Protocol.Discovery.GetResources.Builder newBuilder() {
    return new Energistics.Protocol.Discovery.GetResources.Builder();
  }
  
  /** Creates a new GetResources RecordBuilder by copying an existing Builder */
  public static Energistics.Protocol.Discovery.GetResources.Builder newBuilder(Energistics.Protocol.Discovery.GetResources.Builder other) {
    return new Energistics.Protocol.Discovery.GetResources.Builder(other);
  }
  
  /** Creates a new GetResources RecordBuilder by copying an existing GetResources instance */
  public static Energistics.Protocol.Discovery.GetResources.Builder newBuilder(Energistics.Protocol.Discovery.GetResources other) {
    return new Energistics.Protocol.Discovery.GetResources.Builder(other);
  }
  
  /**
   * RecordBuilder for GetResources instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GetResources>
    implements org.apache.avro.data.RecordBuilder<GetResources> {

    private java.lang.CharSequence uri;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Protocol.Discovery.GetResources.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Protocol.Discovery.GetResources.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GetResources instance */
    private Builder(Energistics.Protocol.Discovery.GetResources other) {
            super(Energistics.Protocol.Discovery.GetResources.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.lang.CharSequence getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public Energistics.Protocol.Discovery.GetResources.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public Energistics.Protocol.Discovery.GetResources.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public GetResources build() {
      try {
        GetResources record = new GetResources();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
