/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.PetroVaultHD.Model.Resource;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Category { 
  None, Metadata, Propety  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Category\",\"namespace\":\"Petrolink.PetroVaultHD.Model.Resource\",\"symbols\":[\"None\",\"Metadata\",\"Propety\"],\"fullName\":\"Petrolink.PetroVaultHD.Model.Resource.Category\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
