/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.PetroVaultHD.Model.Resource;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Condition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Condition\",\"namespace\":\"Petrolink.PetroVaultHD.Model.Resource\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"propertyGroup\",\"type\":[\"null\",\"string\"]},{\"name\":\"operator\",\"type\":{\"type\":\"enum\",\"name\":\"Operator\",\"symbols\":[\"EqualTo\",\"NotEqualTo\"],\"fullName\":\"Petrolink.PetroVaultHD.Model.Resource.Operator\",\"depends\":[]}},{\"name\":\"isExact\",\"type\":\"boolean\"}],\"fullName\":\"Petrolink.PetroVaultHD.Model.Resource.Condition\",\"depends\":[\"Petrolink.PetroVaultHD.Model.Resource.Operator\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence key;
  @Deprecated public java.lang.CharSequence value;
  @Deprecated public java.lang.CharSequence propertyGroup;
  @Deprecated public Petrolink.PetroVaultHD.Model.Resource.Operator operator;
  @Deprecated public boolean isExact;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Condition() {}

  /**
   * All-args constructor.
   */
  public Condition(java.lang.CharSequence key, java.lang.CharSequence value, java.lang.CharSequence propertyGroup, Petrolink.PetroVaultHD.Model.Resource.Operator operator, java.lang.Boolean isExact) {
    this.key = key;
    this.value = value;
    this.propertyGroup = propertyGroup;
    this.operator = operator;
    this.isExact = isExact;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    case 1: return value;
    case 2: return propertyGroup;
    case 3: return operator;
    case 4: return isExact;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.lang.CharSequence)value$; break;
    case 1: value = (java.lang.CharSequence)value$; break;
    case 2: propertyGroup = (java.lang.CharSequence)value$; break;
    case 3: operator = (Petrolink.PetroVaultHD.Model.Resource.Operator)value$; break;
    case 4: isExact = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'key' field.
   */
  public java.lang.CharSequence getKey() {
    return key;
  }

  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.lang.CharSequence value) {
    this.key = value;
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'propertyGroup' field.
   */
  public java.lang.CharSequence getPropertyGroup() {
    return propertyGroup;
  }

  /**
   * Sets the value of the 'propertyGroup' field.
   * @param value the value to set.
   */
  public void setPropertyGroup(java.lang.CharSequence value) {
    this.propertyGroup = value;
  }

  /**
   * Gets the value of the 'operator' field.
   */
  public Petrolink.PetroVaultHD.Model.Resource.Operator getOperator() {
    return operator;
  }

  /**
   * Sets the value of the 'operator' field.
   * @param value the value to set.
   */
  public void setOperator(Petrolink.PetroVaultHD.Model.Resource.Operator value) {
    this.operator = value;
  }

  /**
   * Gets the value of the 'isExact' field.
   */
  public java.lang.Boolean getIsExact() {
    return isExact;
  }

  /**
   * Sets the value of the 'isExact' field.
   * @param value the value to set.
   */
  public void setIsExact(java.lang.Boolean value) {
    this.isExact = value;
  }

  /** Creates a new Condition RecordBuilder */
  public static Petrolink.PetroVaultHD.Model.Resource.Condition.Builder newBuilder() {
    return new Petrolink.PetroVaultHD.Model.Resource.Condition.Builder();
  }
  
  /** Creates a new Condition RecordBuilder by copying an existing Builder */
  public static Petrolink.PetroVaultHD.Model.Resource.Condition.Builder newBuilder(Petrolink.PetroVaultHD.Model.Resource.Condition.Builder other) {
    return new Petrolink.PetroVaultHD.Model.Resource.Condition.Builder(other);
  }
  
  /** Creates a new Condition RecordBuilder by copying an existing Condition instance */
  public static Petrolink.PetroVaultHD.Model.Resource.Condition.Builder newBuilder(Petrolink.PetroVaultHD.Model.Resource.Condition other) {
    return new Petrolink.PetroVaultHD.Model.Resource.Condition.Builder(other);
  }
  
  /**
   * RecordBuilder for Condition instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Condition>
    implements org.apache.avro.data.RecordBuilder<Condition> {

    private java.lang.CharSequence key;
    private java.lang.CharSequence value;
    private java.lang.CharSequence propertyGroup;
    private Petrolink.PetroVaultHD.Model.Resource.Operator operator;
    private boolean isExact;

    /** Creates a new Builder */
    private Builder() {
      super(Petrolink.PetroVaultHD.Model.Resource.Condition.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Petrolink.PetroVaultHD.Model.Resource.Condition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.propertyGroup)) {
        this.propertyGroup = data().deepCopy(fields()[2].schema(), other.propertyGroup);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.operator)) {
        this.operator = data().deepCopy(fields()[3].schema(), other.operator);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isExact)) {
        this.isExact = data().deepCopy(fields()[4].schema(), other.isExact);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Condition instance */
    private Builder(Petrolink.PetroVaultHD.Model.Resource.Condition other) {
            super(Petrolink.PetroVaultHD.Model.Resource.Condition.SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.propertyGroup)) {
        this.propertyGroup = data().deepCopy(fields()[2].schema(), other.propertyGroup);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.operator)) {
        this.operator = data().deepCopy(fields()[3].schema(), other.operator);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isExact)) {
        this.isExact = data().deepCopy(fields()[4].schema(), other.isExact);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'key' field */
    public java.lang.CharSequence getKey() {
      return key;
    }
    
    /** Sets the value of the 'key' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder setKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'key' field has been set */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'key' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder clearKey() {
      key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'value' field */
    public java.lang.CharSequence getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'value' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'propertyGroup' field */
    public java.lang.CharSequence getPropertyGroup() {
      return propertyGroup;
    }
    
    /** Sets the value of the 'propertyGroup' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder setPropertyGroup(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.propertyGroup = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'propertyGroup' field has been set */
    public boolean hasPropertyGroup() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'propertyGroup' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder clearPropertyGroup() {
      propertyGroup = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'operator' field */
    public Petrolink.PetroVaultHD.Model.Resource.Operator getOperator() {
      return operator;
    }
    
    /** Sets the value of the 'operator' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder setOperator(Petrolink.PetroVaultHD.Model.Resource.Operator value) {
      validate(fields()[3], value);
      this.operator = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'operator' field has been set */
    public boolean hasOperator() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'operator' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder clearOperator() {
      operator = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'isExact' field */
    public java.lang.Boolean getIsExact() {
      return isExact;
    }
    
    /** Sets the value of the 'isExact' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder setIsExact(boolean value) {
      validate(fields()[4], value);
      this.isExact = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'isExact' field has been set */
    public boolean hasIsExact() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'isExact' field */
    public Petrolink.PetroVaultHD.Model.Resource.Condition.Builder clearIsExact() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Condition build() {
      try {
        Condition record = new Condition();
        record.key = fieldSetFlags()[0] ? this.key : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.propertyGroup = fieldSetFlags()[2] ? this.propertyGroup : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.operator = fieldSetFlags()[3] ? this.operator : (Petrolink.PetroVaultHD.Model.Resource.Operator) defaultValue(fields()[3]);
        record.isExact = fieldSetFlags()[4] ? this.isExact : (java.lang.Boolean) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
