/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.PetroVaultHD.Model.Resource;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Operator { 
  EqualTo, NotEqualTo  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Operator\",\"namespace\":\"Petrolink.PetroVaultHD.Model.Resource\",\"symbols\":[\"EqualTo\",\"NotEqualTo\"],\"fullName\":\"Petrolink.PetroVaultHD.Model.Resource.Operator\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
