/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.PetroVaultHD.Model.Resource;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ResourceLink extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResourceLink\",\"namespace\":\"Petrolink.PetroVaultHD.Model.Resource\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"id\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"UUID\",\"namespace\":\"Petrolink.PetroVaultHD.Model.DataTypes\",\"size\":16,\"fullName\":\"Petrolink.PetroVaultHD.Model.DataTypes.UUID\",\"depends\":[]}]}],\"fullName\":\"Petrolink.PetroVaultHD.Model.Resource.ResourceLink\",\"depends\":[\"Petrolink.PetroVaultHD.Model.DataTypes.UUID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uri;
  @Deprecated public Petrolink.PetroVaultHD.Model.DataTypes.UUID id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ResourceLink() {}

  /**
   * All-args constructor.
   */
  public ResourceLink(java.lang.CharSequence uri, Petrolink.PetroVaultHD.Model.DataTypes.UUID id) {
    this.uri = uri;
    this.id = id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    case 1: id = (Petrolink.PetroVaultHD.Model.DataTypes.UUID)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public Petrolink.PetroVaultHD.Model.DataTypes.UUID getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(Petrolink.PetroVaultHD.Model.DataTypes.UUID value) {
    this.id = value;
  }

  /** Creates a new ResourceLink RecordBuilder */
  public static Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder newBuilder() {
    return new Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder();
  }
  
  /** Creates a new ResourceLink RecordBuilder by copying an existing Builder */
  public static Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder newBuilder(Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder other) {
    return new Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder(other);
  }
  
  /** Creates a new ResourceLink RecordBuilder by copying an existing ResourceLink instance */
  public static Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder newBuilder(Petrolink.PetroVaultHD.Model.Resource.ResourceLink other) {
    return new Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder(other);
  }
  
  /**
   * RecordBuilder for ResourceLink instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResourceLink>
    implements org.apache.avro.data.RecordBuilder<ResourceLink> {

    private java.lang.CharSequence uri;
    private Petrolink.PetroVaultHD.Model.DataTypes.UUID id;

    /** Creates a new Builder */
    private Builder() {
      super(Petrolink.PetroVaultHD.Model.Resource.ResourceLink.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ResourceLink instance */
    private Builder(Petrolink.PetroVaultHD.Model.Resource.ResourceLink other) {
            super(Petrolink.PetroVaultHD.Model.Resource.ResourceLink.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.lang.CharSequence getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public Petrolink.PetroVaultHD.Model.DataTypes.UUID getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder setId(Petrolink.PetroVaultHD.Model.DataTypes.UUID value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'id' field */
    public Petrolink.PetroVaultHD.Model.Resource.ResourceLink.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ResourceLink build() {
      try {
        ResourceLink record = new ResourceLink();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (Petrolink.PetroVaultHD.Model.DataTypes.UUID) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
