/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.PetroVaultHD.Model.Resource;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SortBy { 
  Name, CreatedDate, LastUpdatedDate, Type, None  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SortBy\",\"namespace\":\"Petrolink.PetroVaultHD.Model.Resource\",\"symbols\":[\"Name\",\"CreatedDate\",\"LastUpdatedDate\",\"Type\",\"None\"],\"fullName\":\"Petrolink.PetroVaultHD.Model.Resource.SortBy\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
