/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Protocol.Store;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DeleteObject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeleteObject\",\"namespace\":\"Energistics.Protocol.Store\",\"fields\":[{\"name\":\"uri\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}],\"messageType\":\"3\",\"protocol\":\"4\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"fullName\":\"Energistics.Protocol.Store.DeleteObject\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.CharSequence> uri;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DeleteObject() {}

  /**
   * All-args constructor.
   */
  public DeleteObject(java.util.List<java.lang.CharSequence> uri) {
    this.uri = uri;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.util.List<java.lang.CharSequence> getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.util.List<java.lang.CharSequence> value) {
    this.uri = value;
  }

  /** Creates a new DeleteObject RecordBuilder */
  public static Energistics.Protocol.Store.DeleteObject.Builder newBuilder() {
    return new Energistics.Protocol.Store.DeleteObject.Builder();
  }
  
  /** Creates a new DeleteObject RecordBuilder by copying an existing Builder */
  public static Energistics.Protocol.Store.DeleteObject.Builder newBuilder(Energistics.Protocol.Store.DeleteObject.Builder other) {
    return new Energistics.Protocol.Store.DeleteObject.Builder(other);
  }
  
  /** Creates a new DeleteObject RecordBuilder by copying an existing DeleteObject instance */
  public static Energistics.Protocol.Store.DeleteObject.Builder newBuilder(Energistics.Protocol.Store.DeleteObject other) {
    return new Energistics.Protocol.Store.DeleteObject.Builder(other);
  }
  
  /**
   * RecordBuilder for DeleteObject instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeleteObject>
    implements org.apache.avro.data.RecordBuilder<DeleteObject> {

    private java.util.List<java.lang.CharSequence> uri;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Protocol.Store.DeleteObject.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Protocol.Store.DeleteObject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DeleteObject instance */
    private Builder(Energistics.Protocol.Store.DeleteObject other) {
            super(Energistics.Protocol.Store.DeleteObject.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.util.List<java.lang.CharSequence> getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public Energistics.Protocol.Store.DeleteObject.Builder setUri(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public Energistics.Protocol.Store.DeleteObject.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public DeleteObject build() {
      try {
        DeleteObject record = new DeleteObject();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
