/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DataAttribute extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataAttribute\",\"namespace\":\"Petrolink.Datatypes\",\"fields\":[{\"name\":\"attributeId\",\"type\":\"int\"},{\"name\":\"attributeValue\",\"type\":{\"type\":\"record\",\"name\":\"DataValue\",\"fields\":[{\"name\":\"item\",\"type\":[\"string\",\"bytes\",\"long\",\"double\",\"boolean\",{\"type\":\"fixed\",\"name\":\"UUID\",\"size\":16,\"fullName\":\"Petrolink.Datatypes.UUID\",\"depends\":[]},{\"type\":\"record\",\"name\":\"DateTime\",\"fields\":[{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"offset\",\"type\":\"double\"}],\"fullName\":\"Petrolink.Datatypes.DateTime\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}],\"fullName\":\"Petrolink.Datatypes.ArrayOfDouble\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfString\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}],\"fullName\":\"Petrolink.Datatypes.ArrayOfString\",\"depends\":[]}]}],\"fullName\":\"Petrolink.Datatypes.DataValue\",\"depends\":[\"Petrolink.Datatypes.UUID\",\"Petrolink.Datatypes.DateTime\",\"Petrolink.Datatypes.ArrayOfDouble\",\"Petrolink.Datatypes.ArrayOfString\"]}}],\"fullName\":\"Petrolink.Datatypes.DataAttribute\",\"depends\":[\"Petrolink.Datatypes.DataValue\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int attributeId;
  @Deprecated public Petrolink.Datatypes.DataValue attributeValue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DataAttribute() {}

  /**
   * All-args constructor.
   */
  public DataAttribute(java.lang.Integer attributeId, Petrolink.Datatypes.DataValue attributeValue) {
    this.attributeId = attributeId;
    this.attributeValue = attributeValue;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attributeId;
    case 1: return attributeValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attributeId = (java.lang.Integer)value$; break;
    case 1: attributeValue = (Petrolink.Datatypes.DataValue)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'attributeId' field.
   */
  public java.lang.Integer getAttributeId() {
    return attributeId;
  }

  /**
   * Sets the value of the 'attributeId' field.
   * @param value the value to set.
   */
  public void setAttributeId(java.lang.Integer value) {
    this.attributeId = value;
  }

  /**
   * Gets the value of the 'attributeValue' field.
   */
  public Petrolink.Datatypes.DataValue getAttributeValue() {
    return attributeValue;
  }

  /**
   * Sets the value of the 'attributeValue' field.
   * @param value the value to set.
   */
  public void setAttributeValue(Petrolink.Datatypes.DataValue value) {
    this.attributeValue = value;
  }

  /** Creates a new DataAttribute RecordBuilder */
  public static Petrolink.Datatypes.DataAttribute.Builder newBuilder() {
    return new Petrolink.Datatypes.DataAttribute.Builder();
  }
  
  /** Creates a new DataAttribute RecordBuilder by copying an existing Builder */
  public static Petrolink.Datatypes.DataAttribute.Builder newBuilder(Petrolink.Datatypes.DataAttribute.Builder other) {
    return new Petrolink.Datatypes.DataAttribute.Builder(other);
  }
  
  /** Creates a new DataAttribute RecordBuilder by copying an existing DataAttribute instance */
  public static Petrolink.Datatypes.DataAttribute.Builder newBuilder(Petrolink.Datatypes.DataAttribute other) {
    return new Petrolink.Datatypes.DataAttribute.Builder(other);
  }
  
  /**
   * RecordBuilder for DataAttribute instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataAttribute>
    implements org.apache.avro.data.RecordBuilder<DataAttribute> {

    private int attributeId;
    private Petrolink.Datatypes.DataValue attributeValue;

    /** Creates a new Builder */
    private Builder() {
      super(Petrolink.Datatypes.DataAttribute.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Petrolink.Datatypes.DataAttribute.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attributeId)) {
        this.attributeId = data().deepCopy(fields()[0].schema(), other.attributeId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.attributeValue)) {
        this.attributeValue = data().deepCopy(fields()[1].schema(), other.attributeValue);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DataAttribute instance */
    private Builder(Petrolink.Datatypes.DataAttribute other) {
            super(Petrolink.Datatypes.DataAttribute.SCHEMA$);
      if (isValidValue(fields()[0], other.attributeId)) {
        this.attributeId = data().deepCopy(fields()[0].schema(), other.attributeId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.attributeValue)) {
        this.attributeValue = data().deepCopy(fields()[1].schema(), other.attributeValue);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'attributeId' field */
    public java.lang.Integer getAttributeId() {
      return attributeId;
    }
    
    /** Sets the value of the 'attributeId' field */
    public Petrolink.Datatypes.DataAttribute.Builder setAttributeId(int value) {
      validate(fields()[0], value);
      this.attributeId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'attributeId' field has been set */
    public boolean hasAttributeId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'attributeId' field */
    public Petrolink.Datatypes.DataAttribute.Builder clearAttributeId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'attributeValue' field */
    public Petrolink.Datatypes.DataValue getAttributeValue() {
      return attributeValue;
    }
    
    /** Sets the value of the 'attributeValue' field */
    public Petrolink.Datatypes.DataAttribute.Builder setAttributeValue(Petrolink.Datatypes.DataValue value) {
      validate(fields()[1], value);
      this.attributeValue = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'attributeValue' field has been set */
    public boolean hasAttributeValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'attributeValue' field */
    public Petrolink.Datatypes.DataAttribute.Builder clearAttributeValue() {
      attributeValue = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public DataAttribute build() {
      try {
        DataAttribute record = new DataAttribute();
        record.attributeId = fieldSetFlags()[0] ? this.attributeId : (java.lang.Integer) defaultValue(fields()[0]);
        record.attributeValue = fieldSetFlags()[1] ? this.attributeValue : (Petrolink.Datatypes.DataValue) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
