/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MessageBody extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageBody\",\"namespace\":\"Petrolink.Datatypes\",\"fields\":[{\"name\":\"item\",\"type\":[\"bytes\",\"string\"]}],\"fullName\":\"Petrolink.Datatypes.MessageBody\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Object item;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public MessageBody() {}

  /**
   * All-args constructor.
   */
  public MessageBody(java.lang.Object item) {
    this.item = item;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return item;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: item = (java.lang.Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'item' field.
   */
  public java.lang.Object getItem() {
    return item;
  }

  /**
   * Sets the value of the 'item' field.
   * @param value the value to set.
   */
  public void setItem(java.lang.Object value) {
    this.item = value;
  }

  /** Creates a new MessageBody RecordBuilder */
  public static Petrolink.Datatypes.MessageBody.Builder newBuilder() {
    return new Petrolink.Datatypes.MessageBody.Builder();
  }
  
  /** Creates a new MessageBody RecordBuilder by copying an existing Builder */
  public static Petrolink.Datatypes.MessageBody.Builder newBuilder(Petrolink.Datatypes.MessageBody.Builder other) {
    return new Petrolink.Datatypes.MessageBody.Builder(other);
  }
  
  /** Creates a new MessageBody RecordBuilder by copying an existing MessageBody instance */
  public static Petrolink.Datatypes.MessageBody.Builder newBuilder(Petrolink.Datatypes.MessageBody other) {
    return new Petrolink.Datatypes.MessageBody.Builder(other);
  }
  
  /**
   * RecordBuilder for MessageBody instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageBody>
    implements org.apache.avro.data.RecordBuilder<MessageBody> {

    private java.lang.Object item;

    /** Creates a new Builder */
    private Builder() {
      super(Petrolink.Datatypes.MessageBody.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Petrolink.Datatypes.MessageBody.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.item)) {
        this.item = data().deepCopy(fields()[0].schema(), other.item);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing MessageBody instance */
    private Builder(Petrolink.Datatypes.MessageBody other) {
            super(Petrolink.Datatypes.MessageBody.SCHEMA$);
      if (isValidValue(fields()[0], other.item)) {
        this.item = data().deepCopy(fields()[0].schema(), other.item);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'item' field */
    public java.lang.Object getItem() {
      return item;
    }
    
    /** Sets the value of the 'item' field */
    public Petrolink.Datatypes.MessageBody.Builder setItem(java.lang.Object value) {
      validate(fields()[0], value);
      this.item = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'item' field has been set */
    public boolean hasItem() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'item' field */
    public Petrolink.Datatypes.MessageBody.Builder clearItem() {
      item = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public MessageBody build() {
      try {
        MessageBody record = new MessageBody();
        record.item = fieldSetFlags()[0] ? this.item : (java.lang.Object) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
