/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Petrolink.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum WellExceptionSeverity { 
  High, Medium, Low  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WellExceptionSeverity\",\"namespace\":\"Petrolink.Datatypes\",\"symbols\":[\"High\",\"Medium\",\"Low\"],\"fullName\":\"Petrolink.Datatypes.WellExceptionSeverity\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
