/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ErrorCodes { 
  ENOROLE, ENOSUPPORTEDPROTOCOLS, EINVALID_MESSAGETYPE, EUNSUPPORTED_PROTOCOL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ErrorCodes\",\"namespace\":\"Energistics.Datatypes\",\"symbols\":[\"ENOROLE\",\"ENOSUPPORTEDPROTOCOLS\",\"EINVALID_MESSAGETYPE\",\"EUNSUPPORTED_PROTOCOL\"],\"fullName\":\"Energistics.Datatypes.ErrorCodes\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
