/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Protocol.DataArray;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GetDataArraySlice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GetDataArraySlice\",\"namespace\":\"Energistics.Protocol.DataArray\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"start\",\"type\":{\"type\":\"array\",\"items\":\"long\"}},{\"name\":\"count\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}],\"messageType\":\"3\",\"protocol\":\"7\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"fullName\":\"Energistics.Protocol.DataArray.GetDataArraySlice\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uri;
  @Deprecated public java.util.List<java.lang.Long> start;
  @Deprecated public java.util.List<java.lang.Long> count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GetDataArraySlice() {}

  /**
   * All-args constructor.
   */
  public GetDataArraySlice(java.lang.CharSequence uri, java.util.List<java.lang.Long> start, java.util.List<java.lang.Long> count) {
    this.uri = uri;
    this.start = start;
    this.count = count;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return start;
    case 2: return count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    case 1: start = (java.util.List<java.lang.Long>)value$; break;
    case 2: count = (java.util.List<java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'start' field.
   */
  public java.util.List<java.lang.Long> getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(java.util.List<java.lang.Long> value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'count' field.
   */
  public java.util.List<java.lang.Long> getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.util.List<java.lang.Long> value) {
    this.count = value;
  }

  /** Creates a new GetDataArraySlice RecordBuilder */
  public static Energistics.Protocol.DataArray.GetDataArraySlice.Builder newBuilder() {
    return new Energistics.Protocol.DataArray.GetDataArraySlice.Builder();
  }
  
  /** Creates a new GetDataArraySlice RecordBuilder by copying an existing Builder */
  public static Energistics.Protocol.DataArray.GetDataArraySlice.Builder newBuilder(Energistics.Protocol.DataArray.GetDataArraySlice.Builder other) {
    return new Energistics.Protocol.DataArray.GetDataArraySlice.Builder(other);
  }
  
  /** Creates a new GetDataArraySlice RecordBuilder by copying an existing GetDataArraySlice instance */
  public static Energistics.Protocol.DataArray.GetDataArraySlice.Builder newBuilder(Energistics.Protocol.DataArray.GetDataArraySlice other) {
    return new Energistics.Protocol.DataArray.GetDataArraySlice.Builder(other);
  }
  
  /**
   * RecordBuilder for GetDataArraySlice instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GetDataArraySlice>
    implements org.apache.avro.data.RecordBuilder<GetDataArraySlice> {

    private java.lang.CharSequence uri;
    private java.util.List<java.lang.Long> start;
    private java.util.List<java.lang.Long> count;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Protocol.DataArray.GetDataArraySlice.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Protocol.DataArray.GetDataArraySlice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.count)) {
        this.count = data().deepCopy(fields()[2].schema(), other.count);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GetDataArraySlice instance */
    private Builder(Energistics.Protocol.DataArray.GetDataArraySlice other) {
            super(Energistics.Protocol.DataArray.GetDataArraySlice.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.count)) {
        this.count = data().deepCopy(fields()[2].schema(), other.count);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.lang.CharSequence getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public Energistics.Protocol.DataArray.GetDataArraySlice.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public Energistics.Protocol.DataArray.GetDataArraySlice.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'start' field */
    public java.util.List<java.lang.Long> getStart() {
      return start;
    }
    
    /** Sets the value of the 'start' field */
    public Energistics.Protocol.DataArray.GetDataArraySlice.Builder setStart(java.util.List<java.lang.Long> value) {
      validate(fields()[1], value);
      this.start = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'start' field has been set */
    public boolean hasStart() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'start' field */
    public Energistics.Protocol.DataArray.GetDataArraySlice.Builder clearStart() {
      start = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'count' field */
    public java.util.List<java.lang.Long> getCount() {
      return count;
    }
    
    /** Sets the value of the 'count' field */
    public Energistics.Protocol.DataArray.GetDataArraySlice.Builder setCount(java.util.List<java.lang.Long> value) {
      validate(fields()[2], value);
      this.count = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'count' field has been set */
    public boolean hasCount() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'count' field */
    public Energistics.Protocol.DataArray.GetDataArraySlice.Builder clearCount() {
      count = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public GetDataArraySlice build() {
      try {
        GetDataArraySlice record = new GetDataArraySlice();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.start = fieldSetFlags()[1] ? this.start : (java.util.List<java.lang.Long>) defaultValue(fields()[1]);
        record.count = fieldSetFlags()[2] ? this.count : (java.util.List<java.lang.Long>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
