/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes.ChannelData;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ChannelRangeInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChannelRangeInfo\",\"namespace\":\"Energistics.Datatypes.ChannelData\",\"fields\":[{\"name\":\"channelId\",\"type\":{\"type\":\"array\",\"items\":\"long\"}},{\"name\":\"startIndex\",\"type\":\"long\"},{\"name\":\"endIndex\",\"type\":\"long\"}],\"fullName\":\"Energistics.Datatypes.ChannelData.ChannelRangeInfo\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.Long> channelId;
  @Deprecated public long startIndex;
  @Deprecated public long endIndex;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ChannelRangeInfo() {}

  /**
   * All-args constructor.
   */
  public ChannelRangeInfo(java.util.List<java.lang.Long> channelId, java.lang.Long startIndex, java.lang.Long endIndex) {
    this.channelId = channelId;
    this.startIndex = startIndex;
    this.endIndex = endIndex;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channelId;
    case 1: return startIndex;
    case 2: return endIndex;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channelId = (java.util.List<java.lang.Long>)value$; break;
    case 1: startIndex = (java.lang.Long)value$; break;
    case 2: endIndex = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'channelId' field.
   */
  public java.util.List<java.lang.Long> getChannelId() {
    return channelId;
  }

  /**
   * Sets the value of the 'channelId' field.
   * @param value the value to set.
   */
  public void setChannelId(java.util.List<java.lang.Long> value) {
    this.channelId = value;
  }

  /**
   * Gets the value of the 'startIndex' field.
   */
  public java.lang.Long getStartIndex() {
    return startIndex;
  }

  /**
   * Sets the value of the 'startIndex' field.
   * @param value the value to set.
   */
  public void setStartIndex(java.lang.Long value) {
    this.startIndex = value;
  }

  /**
   * Gets the value of the 'endIndex' field.
   */
  public java.lang.Long getEndIndex() {
    return endIndex;
  }

  /**
   * Sets the value of the 'endIndex' field.
   * @param value the value to set.
   */
  public void setEndIndex(java.lang.Long value) {
    this.endIndex = value;
  }

  /** Creates a new ChannelRangeInfo RecordBuilder */
  public static Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder newBuilder() {
    return new Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder();
  }
  
  /** Creates a new ChannelRangeInfo RecordBuilder by copying an existing Builder */
  public static Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder newBuilder(Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder other) {
    return new Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder(other);
  }
  
  /** Creates a new ChannelRangeInfo RecordBuilder by copying an existing ChannelRangeInfo instance */
  public static Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder newBuilder(Energistics.Datatypes.ChannelData.ChannelRangeInfo other) {
    return new Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for ChannelRangeInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChannelRangeInfo>
    implements org.apache.avro.data.RecordBuilder<ChannelRangeInfo> {

    private java.util.List<java.lang.Long> channelId;
    private long startIndex;
    private long endIndex;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Datatypes.ChannelData.ChannelRangeInfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channelId)) {
        this.channelId = data().deepCopy(fields()[0].schema(), other.channelId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startIndex)) {
        this.startIndex = data().deepCopy(fields()[1].schema(), other.startIndex);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.endIndex)) {
        this.endIndex = data().deepCopy(fields()[2].schema(), other.endIndex);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ChannelRangeInfo instance */
    private Builder(Energistics.Datatypes.ChannelData.ChannelRangeInfo other) {
            super(Energistics.Datatypes.ChannelData.ChannelRangeInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.channelId)) {
        this.channelId = data().deepCopy(fields()[0].schema(), other.channelId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startIndex)) {
        this.startIndex = data().deepCopy(fields()[1].schema(), other.startIndex);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.endIndex)) {
        this.endIndex = data().deepCopy(fields()[2].schema(), other.endIndex);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'channelId' field */
    public java.util.List<java.lang.Long> getChannelId() {
      return channelId;
    }
    
    /** Sets the value of the 'channelId' field */
    public Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder setChannelId(java.util.List<java.lang.Long> value) {
      validate(fields()[0], value);
      this.channelId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'channelId' field has been set */
    public boolean hasChannelId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'channelId' field */
    public Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder clearChannelId() {
      channelId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'startIndex' field */
    public java.lang.Long getStartIndex() {
      return startIndex;
    }
    
    /** Sets the value of the 'startIndex' field */
    public Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder setStartIndex(long value) {
      validate(fields()[1], value);
      this.startIndex = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'startIndex' field has been set */
    public boolean hasStartIndex() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'startIndex' field */
    public Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder clearStartIndex() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'endIndex' field */
    public java.lang.Long getEndIndex() {
      return endIndex;
    }
    
    /** Sets the value of the 'endIndex' field */
    public Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder setEndIndex(long value) {
      validate(fields()[2], value);
      this.endIndex = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'endIndex' field has been set */
    public boolean hasEndIndex() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'endIndex' field */
    public Energistics.Datatypes.ChannelData.ChannelRangeInfo.Builder clearEndIndex() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ChannelRangeInfo build() {
      try {
        ChannelRangeInfo record = new ChannelRangeInfo();
        record.channelId = fieldSetFlags()[0] ? this.channelId : (java.util.List<java.lang.Long>) defaultValue(fields()[0]);
        record.startIndex = fieldSetFlags()[1] ? this.startIndex : (java.lang.Long) defaultValue(fields()[1]);
        record.endIndex = fieldSetFlags()[2] ? this.endIndex : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
