/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes.ChannelData;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ErrorCodes { 
  EINVALID_URI, EINVALID_CHANNELID, EINVALID_ARGUMENT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ErrorCodes\",\"namespace\":\"Energistics.Datatypes.ChannelData\",\"symbols\":[\"EINVALID_URI\",\"EINVALID_CHANNELID\",\"EINVALID_ARGUMENT\"],\"fullName\":\"Energistics.Datatypes.ChannelData.ErrorCodes\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
