ALTER TABLE alerts ADD COLUMN IF NOT EXISTS investigateBy VARCHAR(64);
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS investigateAt TIMESTAMP ;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS parentClassId VARCHAR(128);
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS parentUuid VARCHAR(128);
