/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes.Object;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NotificationRequestRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotificationRequestRecord\",\"namespace\":\"Energistics.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"includeObjectData\",\"type\":\"boolean\"},{\"name\":\"startTime\",\"type\":\"long\"},{\"name\":\"objectTypes\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}],\"fullName\":\"Energistics.Datatypes.Object.NotificationRequestRecord\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uri;
  @Deprecated public java.lang.CharSequence uuid;
  @Deprecated public boolean includeObjectData;
  @Deprecated public long startTime;
  @Deprecated public java.util.List<java.lang.CharSequence> objectTypes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public NotificationRequestRecord() {}

  /**
   * All-args constructor.
   */
  public NotificationRequestRecord(java.lang.CharSequence uri, java.lang.CharSequence uuid, java.lang.Boolean includeObjectData, java.lang.Long startTime, java.util.List<java.lang.CharSequence> objectTypes) {
    this.uri = uri;
    this.uuid = uuid;
    this.includeObjectData = includeObjectData;
    this.startTime = startTime;
    this.objectTypes = objectTypes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return uuid;
    case 2: return includeObjectData;
    case 3: return startTime;
    case 4: return objectTypes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    case 1: uuid = (java.lang.CharSequence)value$; break;
    case 2: includeObjectData = (java.lang.Boolean)value$; break;
    case 3: startTime = (java.lang.Long)value$; break;
    case 4: objectTypes = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'includeObjectData' field.
   */
  public java.lang.Boolean getIncludeObjectData() {
    return includeObjectData;
  }

  /**
   * Sets the value of the 'includeObjectData' field.
   * @param value the value to set.
   */
  public void setIncludeObjectData(java.lang.Boolean value) {
    this.includeObjectData = value;
  }

  /**
   * Gets the value of the 'startTime' field.
   */
  public java.lang.Long getStartTime() {
    return startTime;
  }

  /**
   * Sets the value of the 'startTime' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.Long value) {
    this.startTime = value;
  }

  /**
   * Gets the value of the 'objectTypes' field.
   */
  public java.util.List<java.lang.CharSequence> getObjectTypes() {
    return objectTypes;
  }

  /**
   * Sets the value of the 'objectTypes' field.
   * @param value the value to set.
   */
  public void setObjectTypes(java.util.List<java.lang.CharSequence> value) {
    this.objectTypes = value;
  }

  /** Creates a new NotificationRequestRecord RecordBuilder */
  public static Energistics.Datatypes.Object.NotificationRequestRecord.Builder newBuilder() {
    return new Energistics.Datatypes.Object.NotificationRequestRecord.Builder();
  }
  
  /** Creates a new NotificationRequestRecord RecordBuilder by copying an existing Builder */
  public static Energistics.Datatypes.Object.NotificationRequestRecord.Builder newBuilder(Energistics.Datatypes.Object.NotificationRequestRecord.Builder other) {
    return new Energistics.Datatypes.Object.NotificationRequestRecord.Builder(other);
  }
  
  /** Creates a new NotificationRequestRecord RecordBuilder by copying an existing NotificationRequestRecord instance */
  public static Energistics.Datatypes.Object.NotificationRequestRecord.Builder newBuilder(Energistics.Datatypes.Object.NotificationRequestRecord other) {
    return new Energistics.Datatypes.Object.NotificationRequestRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for NotificationRequestRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotificationRequestRecord>
    implements org.apache.avro.data.RecordBuilder<NotificationRequestRecord> {

    private java.lang.CharSequence uri;
    private java.lang.CharSequence uuid;
    private boolean includeObjectData;
    private long startTime;
    private java.util.List<java.lang.CharSequence> objectTypes;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Datatypes.Object.NotificationRequestRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Datatypes.Object.NotificationRequestRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uuid)) {
        this.uuid = data().deepCopy(fields()[1].schema(), other.uuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.includeObjectData)) {
        this.includeObjectData = data().deepCopy(fields()[2].schema(), other.includeObjectData);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.startTime)) {
        this.startTime = data().deepCopy(fields()[3].schema(), other.startTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.objectTypes)) {
        this.objectTypes = data().deepCopy(fields()[4].schema(), other.objectTypes);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing NotificationRequestRecord instance */
    private Builder(Energistics.Datatypes.Object.NotificationRequestRecord other) {
            super(Energistics.Datatypes.Object.NotificationRequestRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uuid)) {
        this.uuid = data().deepCopy(fields()[1].schema(), other.uuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.includeObjectData)) {
        this.includeObjectData = data().deepCopy(fields()[2].schema(), other.includeObjectData);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.startTime)) {
        this.startTime = data().deepCopy(fields()[3].schema(), other.startTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.objectTypes)) {
        this.objectTypes = data().deepCopy(fields()[4].schema(), other.objectTypes);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.lang.CharSequence getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'uuid' field */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }
    
    /** Sets the value of the 'uuid' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.uuid = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'uuid' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'includeObjectData' field */
    public java.lang.Boolean getIncludeObjectData() {
      return includeObjectData;
    }
    
    /** Sets the value of the 'includeObjectData' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder setIncludeObjectData(boolean value) {
      validate(fields()[2], value);
      this.includeObjectData = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'includeObjectData' field has been set */
    public boolean hasIncludeObjectData() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'includeObjectData' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder clearIncludeObjectData() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'startTime' field */
    public java.lang.Long getStartTime() {
      return startTime;
    }
    
    /** Sets the value of the 'startTime' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder setStartTime(long value) {
      validate(fields()[3], value);
      this.startTime = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'startTime' field has been set */
    public boolean hasStartTime() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'startTime' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder clearStartTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'objectTypes' field */
    public java.util.List<java.lang.CharSequence> getObjectTypes() {
      return objectTypes;
    }
    
    /** Sets the value of the 'objectTypes' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder setObjectTypes(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.objectTypes = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'objectTypes' field has been set */
    public boolean hasObjectTypes() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'objectTypes' field */
    public Energistics.Datatypes.Object.NotificationRequestRecord.Builder clearObjectTypes() {
      objectTypes = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public NotificationRequestRecord build() {
      try {
        NotificationRequestRecord record = new NotificationRequestRecord();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.uuid = fieldSetFlags()[1] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.includeObjectData = fieldSetFlags()[2] ? this.includeObjectData : (java.lang.Boolean) defaultValue(fields()[2]);
        record.startTime = fieldSetFlags()[3] ? this.startTime : (java.lang.Long) defaultValue(fields()[3]);
        record.objectTypes = fieldSetFlags()[4] ? this.objectTypes : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
