/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes.Object;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Resource extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Resource\",\"namespace\":\"Energistics.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"contentType\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"channelSubscribable\",\"type\":\"boolean\"},{\"name\":\"customData\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"resourceType\",\"type\":\"string\"},{\"name\":\"hasChildren\",\"type\":\"int\"},{\"name\":\"uuid\",\"type\":[\"null\",\"string\"]},{\"name\":\"lastChanged\",\"type\":\"long\"},{\"name\":\"objectNotifiable\",\"type\":\"boolean\"}],\"fullName\":\"Energistics.Datatypes.Object.Resource\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uri;
  @Deprecated public java.lang.CharSequence contentType;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public boolean channelSubscribable;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> customData;
  @Deprecated public java.lang.CharSequence resourceType;
  @Deprecated public int hasChildren;
  @Deprecated public java.lang.CharSequence uuid;
  @Deprecated public long lastChanged;
  @Deprecated public boolean objectNotifiable;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Resource() {}

  /**
   * All-args constructor.
   */
  public Resource(java.lang.CharSequence uri, java.lang.CharSequence contentType, java.lang.CharSequence name, java.lang.Boolean channelSubscribable, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> customData, java.lang.CharSequence resourceType, java.lang.Integer hasChildren, java.lang.CharSequence uuid, java.lang.Long lastChanged, java.lang.Boolean objectNotifiable) {
    this.uri = uri;
    this.contentType = contentType;
    this.name = name;
    this.channelSubscribable = channelSubscribable;
    this.customData = customData;
    this.resourceType = resourceType;
    this.hasChildren = hasChildren;
    this.uuid = uuid;
    this.lastChanged = lastChanged;
    this.objectNotifiable = objectNotifiable;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return contentType;
    case 2: return name;
    case 3: return channelSubscribable;
    case 4: return customData;
    case 5: return resourceType;
    case 6: return hasChildren;
    case 7: return uuid;
    case 8: return lastChanged;
    case 9: return objectNotifiable;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    case 1: contentType = (java.lang.CharSequence)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    case 3: channelSubscribable = (java.lang.Boolean)value$; break;
    case 4: customData = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 5: resourceType = (java.lang.CharSequence)value$; break;
    case 6: hasChildren = (java.lang.Integer)value$; break;
    case 7: uuid = (java.lang.CharSequence)value$; break;
    case 8: lastChanged = (java.lang.Long)value$; break;
    case 9: objectNotifiable = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'contentType' field.
   */
  public java.lang.CharSequence getContentType() {
    return contentType;
  }

  /**
   * Sets the value of the 'contentType' field.
   * @param value the value to set.
   */
  public void setContentType(java.lang.CharSequence value) {
    this.contentType = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'channelSubscribable' field.
   */
  public java.lang.Boolean getChannelSubscribable() {
    return channelSubscribable;
  }

  /**
   * Sets the value of the 'channelSubscribable' field.
   * @param value the value to set.
   */
  public void setChannelSubscribable(java.lang.Boolean value) {
    this.channelSubscribable = value;
  }

  /**
   * Gets the value of the 'customData' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getCustomData() {
    return customData;
  }

  /**
   * Sets the value of the 'customData' field.
   * @param value the value to set.
   */
  public void setCustomData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.customData = value;
  }

  /**
   * Gets the value of the 'resourceType' field.
   */
  public java.lang.CharSequence getResourceType() {
    return resourceType;
  }

  /**
   * Sets the value of the 'resourceType' field.
   * @param value the value to set.
   */
  public void setResourceType(java.lang.CharSequence value) {
    this.resourceType = value;
  }

  /**
   * Gets the value of the 'hasChildren' field.
   */
  public java.lang.Integer getHasChildren() {
    return hasChildren;
  }

  /**
   * Sets the value of the 'hasChildren' field.
   * @param value the value to set.
   */
  public void setHasChildren(java.lang.Integer value) {
    this.hasChildren = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'lastChanged' field.
   */
  public java.lang.Long getLastChanged() {
    return lastChanged;
  }

  /**
   * Sets the value of the 'lastChanged' field.
   * @param value the value to set.
   */
  public void setLastChanged(java.lang.Long value) {
    this.lastChanged = value;
  }

  /**
   * Gets the value of the 'objectNotifiable' field.
   */
  public java.lang.Boolean getObjectNotifiable() {
    return objectNotifiable;
  }

  /**
   * Sets the value of the 'objectNotifiable' field.
   * @param value the value to set.
   */
  public void setObjectNotifiable(java.lang.Boolean value) {
    this.objectNotifiable = value;
  }

  /** Creates a new Resource RecordBuilder */
  public static Energistics.Datatypes.Object.Resource.Builder newBuilder() {
    return new Energistics.Datatypes.Object.Resource.Builder();
  }
  
  /** Creates a new Resource RecordBuilder by copying an existing Builder */
  public static Energistics.Datatypes.Object.Resource.Builder newBuilder(Energistics.Datatypes.Object.Resource.Builder other) {
    return new Energistics.Datatypes.Object.Resource.Builder(other);
  }
  
  /** Creates a new Resource RecordBuilder by copying an existing Resource instance */
  public static Energistics.Datatypes.Object.Resource.Builder newBuilder(Energistics.Datatypes.Object.Resource other) {
    return new Energistics.Datatypes.Object.Resource.Builder(other);
  }
  
  /**
   * RecordBuilder for Resource instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Resource>
    implements org.apache.avro.data.RecordBuilder<Resource> {

    private java.lang.CharSequence uri;
    private java.lang.CharSequence contentType;
    private java.lang.CharSequence name;
    private boolean channelSubscribable;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> customData;
    private java.lang.CharSequence resourceType;
    private int hasChildren;
    private java.lang.CharSequence uuid;
    private long lastChanged;
    private boolean objectNotifiable;

    /** Creates a new Builder */
    private Builder() {
      super(Energistics.Datatypes.Object.Resource.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Energistics.Datatypes.Object.Resource.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contentType)) {
        this.contentType = data().deepCopy(fields()[1].schema(), other.contentType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channelSubscribable)) {
        this.channelSubscribable = data().deepCopy(fields()[3].schema(), other.channelSubscribable);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customData)) {
        this.customData = data().deepCopy(fields()[4].schema(), other.customData);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.resourceType)) {
        this.resourceType = data().deepCopy(fields()[5].schema(), other.resourceType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.hasChildren)) {
        this.hasChildren = data().deepCopy(fields()[6].schema(), other.hasChildren);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.uuid)) {
        this.uuid = data().deepCopy(fields()[7].schema(), other.uuid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lastChanged)) {
        this.lastChanged = data().deepCopy(fields()[8].schema(), other.lastChanged);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.objectNotifiable)) {
        this.objectNotifiable = data().deepCopy(fields()[9].schema(), other.objectNotifiable);
        fieldSetFlags()[9] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Resource instance */
    private Builder(Energistics.Datatypes.Object.Resource other) {
            super(Energistics.Datatypes.Object.Resource.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contentType)) {
        this.contentType = data().deepCopy(fields()[1].schema(), other.contentType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channelSubscribable)) {
        this.channelSubscribable = data().deepCopy(fields()[3].schema(), other.channelSubscribable);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customData)) {
        this.customData = data().deepCopy(fields()[4].schema(), other.customData);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.resourceType)) {
        this.resourceType = data().deepCopy(fields()[5].schema(), other.resourceType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.hasChildren)) {
        this.hasChildren = data().deepCopy(fields()[6].schema(), other.hasChildren);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.uuid)) {
        this.uuid = data().deepCopy(fields()[7].schema(), other.uuid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lastChanged)) {
        this.lastChanged = data().deepCopy(fields()[8].schema(), other.lastChanged);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.objectNotifiable)) {
        this.objectNotifiable = data().deepCopy(fields()[9].schema(), other.objectNotifiable);
        fieldSetFlags()[9] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.lang.CharSequence getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public Energistics.Datatypes.Object.Resource.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public Energistics.Datatypes.Object.Resource.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'contentType' field */
    public java.lang.CharSequence getContentType() {
      return contentType;
    }
    
    /** Sets the value of the 'contentType' field */
    public Energistics.Datatypes.Object.Resource.Builder setContentType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.contentType = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'contentType' field has been set */
    public boolean hasContentType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'contentType' field */
    public Energistics.Datatypes.Object.Resource.Builder clearContentType() {
      contentType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public Energistics.Datatypes.Object.Resource.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'name' field */
    public Energistics.Datatypes.Object.Resource.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'channelSubscribable' field */
    public java.lang.Boolean getChannelSubscribable() {
      return channelSubscribable;
    }
    
    /** Sets the value of the 'channelSubscribable' field */
    public Energistics.Datatypes.Object.Resource.Builder setChannelSubscribable(boolean value) {
      validate(fields()[3], value);
      this.channelSubscribable = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'channelSubscribable' field has been set */
    public boolean hasChannelSubscribable() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'channelSubscribable' field */
    public Energistics.Datatypes.Object.Resource.Builder clearChannelSubscribable() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'customData' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getCustomData() {
      return customData;
    }
    
    /** Sets the value of the 'customData' field */
    public Energistics.Datatypes.Object.Resource.Builder setCustomData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.customData = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'customData' field has been set */
    public boolean hasCustomData() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'customData' field */
    public Energistics.Datatypes.Object.Resource.Builder clearCustomData() {
      customData = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'resourceType' field */
    public java.lang.CharSequence getResourceType() {
      return resourceType;
    }
    
    /** Sets the value of the 'resourceType' field */
    public Energistics.Datatypes.Object.Resource.Builder setResourceType(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.resourceType = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'resourceType' field has been set */
    public boolean hasResourceType() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'resourceType' field */
    public Energistics.Datatypes.Object.Resource.Builder clearResourceType() {
      resourceType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'hasChildren' field */
    public java.lang.Integer getHasChildren() {
      return hasChildren;
    }
    
    /** Sets the value of the 'hasChildren' field */
    public Energistics.Datatypes.Object.Resource.Builder setHasChildren(int value) {
      validate(fields()[6], value);
      this.hasChildren = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'hasChildren' field has been set */
    public boolean hasHasChildren() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'hasChildren' field */
    public Energistics.Datatypes.Object.Resource.Builder clearHasChildren() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'uuid' field */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }
    
    /** Sets the value of the 'uuid' field */
    public Energistics.Datatypes.Object.Resource.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.uuid = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'uuid' field */
    public Energistics.Datatypes.Object.Resource.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'lastChanged' field */
    public java.lang.Long getLastChanged() {
      return lastChanged;
    }
    
    /** Sets the value of the 'lastChanged' field */
    public Energistics.Datatypes.Object.Resource.Builder setLastChanged(long value) {
      validate(fields()[8], value);
      this.lastChanged = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'lastChanged' field has been set */
    public boolean hasLastChanged() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'lastChanged' field */
    public Energistics.Datatypes.Object.Resource.Builder clearLastChanged() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'objectNotifiable' field */
    public java.lang.Boolean getObjectNotifiable() {
      return objectNotifiable;
    }
    
    /** Sets the value of the 'objectNotifiable' field */
    public Energistics.Datatypes.Object.Resource.Builder setObjectNotifiable(boolean value) {
      validate(fields()[9], value);
      this.objectNotifiable = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'objectNotifiable' field has been set */
    public boolean hasObjectNotifiable() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'objectNotifiable' field */
    public Energistics.Datatypes.Object.Resource.Builder clearObjectNotifiable() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    public Resource build() {
      try {
        Resource record = new Resource();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.contentType = fieldSetFlags()[1] ? this.contentType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.channelSubscribable = fieldSetFlags()[3] ? this.channelSubscribable : (java.lang.Boolean) defaultValue(fields()[3]);
        record.customData = fieldSetFlags()[4] ? this.customData : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[4]);
        record.resourceType = fieldSetFlags()[5] ? this.resourceType : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.hasChildren = fieldSetFlags()[6] ? this.hasChildren : (java.lang.Integer) defaultValue(fields()[6]);
        record.uuid = fieldSetFlags()[7] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.lastChanged = fieldSetFlags()[8] ? this.lastChanged : (java.lang.Long) defaultValue(fields()[8]);
        record.objectNotifiable = fieldSetFlags()[9] ? this.objectNotifiable : (java.lang.Boolean) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
